### ISSUE TITLE
PS Module

### ISSUE THREAD

**Issue by flyboarder** [nightroman/Invoke-Build#14]
Can we get psd1 and psm1 files generated for this project so it is detected as an actual PSModule?

**Comment by nightroman** [comment]
@flyboarder Maybe. But I have to understand why. Invoke-Build is not a module, it is a script. Why would you want it to be a module? What issues or difficulties do you experience because Invoke-Build is not a module?

Take a look at

- "Why is it a script?" at [Design-Notes](https://github.com/nightroman/Invoke-Build/wiki/Design-Notes)
- Some known script [Module](https://github.com/nightroman/PowerShellTraps/tree/master/Module) issues at [PowerShellTraps](https://github.com/nightroman/PowerShellTraps)

**Comment by nightroman** [comment]
I am closing it. Feel free to reopen if there is some more input.

**Comment by nightroman** [comment]
@flyboarder, your wish finally came true. Now it makes sense to distribute Invoke-Build as a module because we have PowerShellGet and the official PowerShell gallery. See the README.

**Comment by flyboarder** [comment]
@nightroman yay!! Thanks so much!
