### ISSUE TITLE
Problem with the automatic bootstrapping

### ISSUE THREAD

**Issue by eanyanwu** [nightroman/Invoke-Build#152]
First, thank you for your work with invoke-build. It's hard to overstate how helpful this tool has been.

I was looking around the repo, hoping to discover functionality I did not know about. I found the README about [a way to automatically bootstrap invoke-build](https://github.com/nightroman/Invoke-Build/blob/master/Tasks/Paket/Project.build.ps1) 

This is incredibly useful for controlling which version of invoke build is used. I don't need to have all developers upgrade the versions on their machines, I can just bump the version and push the change.

However, the proof of concept does not seem to be working 🤔  for a very weird reason.

The first time `.\repro.ps1 Test` is invoked, it works. But subsequent invocations fail with `A positional parameter cannot be found that accepts argument 'Test'`

What's even weirder is that if i modify the file, save it, then run `.\repro.ps1 Test` again, it works once. Then fails again on subsequent invocations.

It looks like the problem is with invoke-build because if I comment out the call to Invoke-Build, this parameter parsing problem does not occur

repro.ps1
```
param(
    [Parameter(Position=0)][string[]]   $Tasks
)

if ([System.IO.Path]::GetFileName($MyInvocation.ScriptName) -ne "Invoke-Build.ps1") {
    # Call invoke build
    Invoke-Build -Task $Tasks -File $MyInvocation.MyCommand.Path @PSBoundParameters

    return
}


task Test {
    Write-Build White "Hello World"
}
```

Thank you for your time!

**Comment by nightroman** [comment]
I cannot repro the problem. How do you call the script `repro.ps1` exactly?

**Comment by nightroman** [comment]
Yes, interesting. Let me think about it...
What is your `gcm Invoke-Build` ?

**Comment by nightroman** [comment]
Yes, I installed the module explicitly and got the issues reproduced. Ok, I am on it.

**Comment by nightroman** [comment]
So far I would say it's a weird PowerShell bug, repro in v5+ (v2 mode works fine). I should find a workaround for the IB scenario. And try to report it to PowerShell, too.

It's really weird and unfortunate... Thank you for catching and reporting this.

**Comment by nightroman** [comment]
One lame workaround seems to be using `-tasks` explicitly, i.e. `.\repro.ps1 -tasks Test`. But it is not good enough.

No insights yet :(

**Comment by nightroman** [comment]
After all, the problem is in Invoke-Build due to this line
https://github.com/nightroman/Invoke-Build/blob/69b0e47678e945a34ab3f5b240e7736776f8e686/Invoke-Build.ps1#L121

We change the script parameter attributes from positional to named. It looked
like a good idea to enforce using parameter names for build scripts parameters.
But PowerShell v5+ seems to be caching once obtained parameters and attributes.
Thus, Invoke-Build must not alter them.

I am going to remove this line. The problem will be solved. But I need some
more time to test this and think, too.

As a result, it will be possible to use build script positional parameters, e.g.

    Invoke-Build myTask myFile.ps1 42 bar
    
where `42` and `bar` are positional parameters of `myFile.ps1`.
Some people may even find this useful in some cases.

**Comment by eanyanwu** [comment]
I'm not familiar with the code, but your explanation makes sense. Thank you for looking into this. 
This works well, because since I now have the automatic bootstrapping in place, I can quickly change the version whenever you release it 👍

**Comment by nightroman** [comment]
All looks good, I pushed v5.5.3 with the fix.
Thank you for the detailed report.
Happy building!
