### ISSUE TITLE
Consider automatically setting process current directory

### ISSUE THREAD

**Issue by zanaptak** [nightroman/Invoke-Build#168]
I had occasion to drop down to .NET filesystem calls in a task and discovered that, although Invoke-Build is setting the PS location, that does not carry over to the overall process working dir (used by .NET APIs), [by design because of runspaces](https://github.com/PowerShell/PowerShell/issues/9829). So, relative paths are only safe in native PS commands, but not external calls if the initial PS process was not launched from the build root.

Although easily worked around by setting `[Environment]::CurrentDirectory = $BuildRoot` myself, or using `Resolve-Path` before all .NET API calls, I feel it would be reasonable and convenient for Invoke-Build to set process working dir along with the PS location by default, consistent with the goal of a known start location for tasks. The generic concern about runspaces doesn't necessarily have to extend to a purposeful build tool with a defined, documented behavior.

**Comment by nightroman** [comment]
I agree it's tempting and would be useful in some cases. But PowerShell does not do this and Invoke-Build follows.

You are right, it's easy to do on your own. This is universally known as a bad practice. But it's up to you, your code, your rules. If something is not working due to this then you "know why". Invoke-Build does not have this kind of freedom.

Invoke-Build is designed for complex scenarios including nested builds and parallel builds. Changing PWD in each called build script introduces issues. In fact scripts cannot rely on the fact that their $BuildRoot is PWD. Because other scripts may be invoked before or at the same.

I am going to close this. Sorry if this disappoints you.
