### ISSUE TITLE
`-Before/-After` are not honoured if the referenced task has no jobs

### ISSUE THREAD

**Issue by Kieranties** [nightroman/Invoke-Build#17]
I've been putting together a little project built around Invoke-Build.  The intention is to define a standard lifecycle of tasks that can then be hooked into using `-Before` and `-After`.
I've found an issue where should the task being targeted with `-Before/After` have an empty job list, then the tasks fire in what looks like alphabetical order rather than honouring the expected arrangement,

### Repro

if I define a `.build.ps1` as follows
```powershell

# Import features
. .\alpha.ps1
. .\beta.ps1

# Default Task
Task . -Jobs Build

# Lifecycle
Task Clean
Task Build -Jobs Clean
Task Pack -Jobs Build
```

And I create alpha.ps1
```powershell
task Clean.Alpha -Jobs { Write-Build 10 "alpha" } -After Clean
```

and beta.ps1
```powershell
task Clean.Beta -Jobs { Write-Build 10 "beta" } -Before Clean
```

When the build is executed, I would expect the tasks to fire in the order: `Clean.Beta`, `Clean`, `Clean.Alpha`.  However the tasks fire in the order `Clean.Alpha`, `Clean.Beta`, `Clean`.
```powershell
C:\Users\Kieranties\Desktop\repro
> .\Invoke-Build.ps1
Build . C:\Users\Kieranties\Desktop\repro\.build.ps1
Task /./Build/Clean/Clean.Alpha
alpha
Done /./Build/Clean/Clean.Alpha 00:00:00.0080036
Task /./Build/Clean/Clean.Beta
beta
Done /./Build/Clean/Clean.Beta 00:00:00.0069889
Done /./Build/Clean 00:00:00.0210044
Done /./Build 00:00:00.0250046
Done /. 00:00:00.0290171
Build succeeded. 5 tasks, 0 errors, 0 warnings 00:00:00.0610152
```

### Workaround

To work around the issue, the task being targeted with `-Before/-After` must declare a job.  This job can be empty.  E.g. Declaring the `Clean` task as `task Clean -Jobs {}` and running the build again gives the expected result

```powershell
C:\Users\Kieranties\Desktop\repro
> .\Invoke-Build.ps1
Build . C:\Users\Kieranties\Desktop\repro\.build.ps1
Task /./Build/Clean/Clean.Beta
beta
Done /./Build/Clean/Clean.Beta 00:00:00.0060157
Task /./Build/Clean
Task /./Build/Clean/Clean.Alpha
alpha
Done /./Build/Clean/Clean.Alpha 00:00:00.0059994
Done /./Build/Clean 00:00:00.0250031
Done /./Build 00:00:00.0290026
Done /. 00:00:00.0330021
Build succeeded. 5 tasks, 0 errors, 0 warnings 00:00:00.0570023
```

**Comment by nightroman** [comment]
This is an interesting and subtle issue. It was considered and the current
behaviour was documented:

    . Invoke-Build
    help task -Parameter Before

shows

    -Before
        Tells to add this task to job lists of the specified tasks. It is
        inserted before the first script job, if any, or added to the end.

That is, if an altered task has no actions (no script jobs) then a *Before*
task is added to the end of jobs. This approach may look counter-intuitive in
your case but it preserves the order of added *Before* tasks. If multiple
*Before* tasks are inserted in the beginning of jobs then their order would be
reversed. This would be counter-intuitive, too.

Also, inserting *Before* tasks in the beginning of jobs would is not good for
other reasons. Suppose we have

    task Task2 -Jobs Task1
    ...
    task Before -Before Task2

The above would be transformed into

    task Task2 -Jobs Before, Task1

Maybe it is fine so far. But if later an action is added to *Task2*:

    task Task2 -Jobs Task1, {some code}

then

    task Task2 -Jobs Before, Task1, {some code}

is not so good because we normally want to add something exactly before task
own actions, not before referenced tasks. That is we want this:

    task Task2 -Jobs Task1, Before, {some code}

That is why it was decided to add *Before* tasks to the end if there is no
action, because an action can be added later.

> To work around the issue, the task being targeted with -Before/-After must declare a job.

Correct. Strictly speaking, not just a job, but a script job, an action. Just
having a job, i.e. a reference to another task, is not enough. See the above
example case.

As far as the workaround existed and the issue was rare, the current design was
fine so far. But if it causes issues then let's think of some improvements.
What would you propose?

Some thought. The whole idea of *Before* and *After* tasks, i.e. altering some
tasks from outside, is somewhat a hack. But it existed in *MSBuild* and it was
adopted. It is useful in some special cases, it helped me a few times. But as
far as it is a "hack", it would be reasonable to keep it as simple as possible.

**Comment by nightroman** [comment]
I think there is a simple solution. In *Invoke-Build.ps1* replace

        foreach(${private:**} in ${*a}.Values) {
            if (${**}.Before) {${**}.Before | *AB ${**}.Name 1}
            if (${**}.After) {${**}.After | *AB ${**}.Name}
        }

with two loops

        foreach(${private:**} in ${*a}.Values) {
            if (${**}.Before) {${**}.Before | *AB ${**}.Name 1}
        }
        foreach(${private:**} in ${*a}.Values) {
            if (${**}.After) {${**}.After | *AB ${**}.Name}
        }

That is, at first we process all *Before* as usual and then only all *After*.
It looks like the problem is resolved and all previous design decisions are
happy, too.

Let me know if it works for you. I will test this on my own. If all is fine
then it makes sense to release this change. It is potentially breaking but
problems should be rare.

**Comment by Kieranties** [comment]
First, thanks for pointing I that I should have read the docs _properly_.  One of the main reasons for moving to Invoke-Build from Psake is the excellent documentation!

I view _Before_ and _After_ tasks as an excellent feature of Invoke-Build.  I'm looking at providing a modular build system such that a conventional build lifecycle can be extended by bringing in build features specific to those modules.  E.g. a module containing msbuild tasks, a module containing dnx build tasks, a module containing nunit tasks, a module containing xunit tasks

_Before_ and _After_ are key to this as it removes the requirement for developers to manual.  By having those tasks target a step using Before/After they automatically hook into the process.  So far, this has worked quite well.

I've tested the suggested change and it does indeed seem to resolve the issue for me.  Many thanks for the quick response.

**Comment by nightroman** [comment]
Great! Thank you for reporting this issue. It is a design flaw with no doubts, especially taking into account its very simple fix. I will release the updated version soon.

**Comment by Kieranties** [comment]
:+1: for use of Pandoc too!
