### ISSUE TITLE
Changing of $BuildRoot does not change CLR's current directory

### ISSUE THREAD

**Issue by GreatTeacherBasshead** [nightroman/Invoke-Build#174]
Hi Roman,

Imaging this file structure:

> \\
> \buildScripts\build.ps1
> \src\config.xml
>  \.....

Imaging this code in `build.ps1`:
```powershell
$BuildRoot = "\"

task UpdateXml {
  $xml = New-Object xml
  $xml.Load("src\config.xml")
}
```

I get an error:
`Exception calling "Load" with "1" argument(s): "Could not find a part of the path '\buildScripts\src\config.xml'."`

This is not the issue of Invoke-Build, but PowerShell itself, because it does not change `[System.IO.Directory]::GetCurrentDirectory()` even when you `cd` to other directories.
And I can use some workarounds, like `[xml]$xml = Get-Content ...` or `[System.IO.Directory]::SetCurrentDirectory()` manually.

The question is - what do you think, should setting `$BuildRoot` also run `[System.IO.Directory]::SetCurrentDirectory()`?

**Comment by nightroman** [comment]
Hi @GreatTeacherBasshead 

I hope you are not disappointed to know that this is by design. It's in fact
the PowerShell feature, `Set-Location` does not change the process current
directory. It's a notorious issue and the source of mistakes (for not careful
programmers :)), yes.

But it has advantages, too, and protects from other problems. E.g. scripts
(including build scripts) may run in parallel in the same process. Thus, if
they relay on the process current directory and change it then other running
scripts have issues.

We have to remember and deal with this fact. It's not an issue for properly
designed PowerShell commands. It's not an issue for running applications
(PowerShell sets their proper start directory).

It's only the issue on calling .NET API which relays on the process current
directory. Do not let them! Pass full paths always. In your case,

    $xml.Load("$BuildRoot\src\config.xml")

**Comment by GreatTeacherBasshead** [comment]
Many thanks for the clarification!
