### ISSUE TITLE
Conditional Task Issue?

### ISSUE THREAD

**Issue by zloeber** [nightroman/Invoke-Build#28]
I'm not certain if I'm possibly just missing something or what but I cannot get conditional tasks to work. Here is an extremely simple example.

```
#Synopsis: Validate script requirements are met, load required modules, and load build tools.
task Configure {
    # If we made it this far then we are configured!
    $Script:IsConfigured = $True
        Write-Host 'configured!'
}, TestConfigure

task TestConfigure -If ($Script:IsConfigured -eq $true) {
    Write-Host 'configured...for certain!'
}
```

If I run invoke-build Configure it will always skip the TestConfigure task.

**Comment by nightroman** [comment]
Task parameters `If`, `Inputs`, and `Outputs` can be either script blocks
evaluated on task invocation or other values evaluated on task definition.

In your case the value for `If` may change after adding tasks and you want to
use the current changed value on invocation of the task `TestConfigure`. So use
the script block:

    task TestConfigure -If {$Script:IsConfigured} {
        Write-Host 'configured...for certain!'
    }

You should use `-If $Script:IsConfigured` only if `$Script:IsConfigured` does
not change or you specifically want to check for the original value, not
changed during the build.

----

If values for `If` (or `Inputs`, `Outputs`) do not change during the build then
it does not matter what to use, `-If {}` or `-If ()`. But if the expression is
complex/expensive you may choose `-If {}` in order to avoid evaluation if a
task is not invoked at all in the build. On the other hand, if you want to
catch potential problems earlier, at a task definition, then you still may
want to use `-If ()`.

Should we improve help perhaps? Here is the current:

    0> . Invoke-Build
    0> help task -Parameter If

    -If
        Specifies the optional condition to be evaluated. If the condition
        evaluates to false then the task is not invoked.

        The value is a script block evaluated on task invocation or an object
        treated as Boolean on definition. On WhatIf a script block is treated
        as true without invocation.

        If the task is called several times then it is possible that the task
        is skipped at first but invoked later when the script block gets true.

**Comment by zloeber** [comment]
Ok, so I was 'just missing something' then :)

The difference between () and {} is nuanced but it makes sense. I swear I was trying to do the appropriate amount of RTFM before asking. I'd maybe modify the documentation slightly to show both scenarios.

```
-If
    Specifies the optional condition to be evaluated. If the condition
    evaluates to false then the task is not invoked. The condition can be
    defined in one of two ways depending on your requirements.

    Using script block notation (curly braces) the condition will be evaluated
    dynamically upon task invocation. This is ideal for tasks that may be
    run multiple times and are skipped at first but invoked later when the 
    script block becomes true. 

    Example:
        task SomeTask -If {$SomeCondition} {...}
    
    Using standard Boolean notation (parenthesis) the condition will only 
    be evaluated when the task is loaded into the build engine. A use case
    for this notation might be evaluating parameters that are passed into 
    the build.
    
    Example:
        task SomeTask -If ($SomeCondition) {...}

    On WhatIf a script block is treated as true without invocation using 
    script block notation but not if the condition is defined in Boolean 
    notation.
```

Or something like that?

Regardless, thanks for clarifying for me and thank you for the excellent project!

**Comment by nightroman** [comment]
Thank you for the suggested improved help. I like it and will use it in vNext.
