### ISSUE TITLE
Parallel builds scope

### ISSUE THREAD

**Issue by lsgroi** [nightroman/Invoke-Build#38]
Given the script `script.ps1`
```powershell
$script:Foo = "This is foo"
```
and the build script `build.ps1`
```powershell
Task Foo {
	$Foo
}
```
using `Invoke-Build` I have access to the script scope variable
```
PS C:\temp> .  .\script.ps1

PS C:\temp> Invoke-Build -File .\build.ps1 -Task Foo
Build Foo C:\temp\build.ps1
Task /Foo
This is foo
Done /Foo 00:00:00.0080051
Build succeeded. 1 tasks, 0 errors, 0 warnings 00:00:00.1170883
```
while I cannot using `Invoke-Builds`
```
PS C:\temp> .  .\script.ps1

PS C:\temp> Invoke-Builds @(@{File=".\build.ps1"; Task='Foo'})
(1/1) C:\temp\build.ps1
Build (1/1) C:\temp\build.ps1:
Build Foo C:\temp\build.ps1
Task /Foo
Done /Foo 00:00:00.0030020
Build succeeded. 1 tasks, 0 errors, 0 warnings 00:00:00.0140088
Build (1/1) C:\temp\build.ps1 succeeded.
Tasks: 1 tasks, 0 errors, 0 warnings
Builds succeeded. 1 builds, 0 failed 00:00:00.1901150
```
I wonder if the behavior is by design and if there's a way to achieve so. 
Consider that for simplicity I have used a variable in my example but my real use case involves script scope functions. I have a script which orchestrate the invocation of builds with common initialization.

**Comment by nightroman** [comment]
Yes, this by design, and rather by PowerShell design than Invoke-Build.
Invoke-Build just runs parallel builds in separate runspaces created by
`[PowerShell]::Create()`. Forget about Invoke-Build for a moment and try to
invoke some code using this way. You will see that nothing from the current
scope is propagated to a new runspace.

Alas, with the power of parallel processing come some rules and limitations.

What you can do. In your simple case use parameters in order to pass data to
parallel builds explicitly. That is declare the parameter in the build script:

````powershell
    # build.ps1
    
    param($Foo)

    Task Foo {
        $Foo
    }
````

and invoke it with passing the variable `$Foo` and the parameter:

````powerShell
    . .\script.ps1

    Invoke-Builds @(@{File=".\build.ps1"; Task='Foo'; Foo=$Foo})
````

Similarly, pass other required data as parameters. If you have too many
items, consider using an object with properties or a hashtable.

What about scope functions? With parallel processing in mind you have to
redesign something anyway. It is up to you how, there are many ways. For
example, put shared functions to a module, or another dot-sourced script,
then import them to a calling script and to a build script, too. Or define
and use functions as script blocks and pass them to a build script as data
via parameters (not neat perhaps but handy in some cases).
