### ISSUE TITLE
Invoke-Build says success but the Appveyor build fails

### ISSUE THREAD

**Issue by DexterPOSH** [nightroman/Invoke-Build#46]
Recently switched to using Invoke-Build from psake.
Used the ConvertFrom-Psake.ps1 to convert the build script to be used with Invoke-Build.

The invoke-build says that the build succeeded and an exception is thrown which marks the overall build in appveyor as failed.
![image](https://cloud.githubusercontent.com/assets/6275375/21671595/71749cc0-d342-11e6-9966-d6dfbc8c512d.png)

 See the Appveryor build failing [here](https://ci.appveyor.com/project/DexterPOSH/psremotely) and the branch [here](https://github.com/DexterPOSH/PSRemotely/tree/develop).
I tried to repro this on a Server2016 VM running WMF5.1 to see where the exception is being thrown but it does not throw it on the VM.

![image](https://cloud.githubusercontent.com/assets/6275375/21671581/63854e66-d342-11e6-869c-53872f2cf5a7.png)

Running out of ideas on how to debug this. Is there something, which I am missing here ?

**Comment by nightroman** [comment]
The error message is strange. I am not sure it is the real cause of the problem.

Here is a potential problem which I can see right away.

Appveyor calls the build as

    - ps: . .\build.ps1

The script build.ps1 contains the last line (not removed after conversion from psake)

    exit ( [int]( -not $psake.build_success ) )

`$psake` is not defined, so that `$psake.build_success` is null and this results in

    exit 1

Then

> I tried to repro this on a Server2016 VM running WMF5.1

How do you run the build in this case? Exactly, what is the command, what is
the host, how do you invoke this command? Can you check `$LastExitCode`
immediately after it? Is it 1? And then remove the line with `$psake`.
What is the code after that, 0?

Anyway, try to remove the line with `$psake` first and let me know if this is it.
