### ISSUE TITLE
Cannot resolve '15.0' with MSBuild version 15

### ISSUE THREAD

**Issue by aevv** [nightroman/Invoke-Build#55]
Microsoft no longer use the registry to store the location of the MSBuild executable, so attempting to use version 15 of MSBuild from VS2017 causes an error. This occurs at https://github.com/nightroman/Invoke-Build/blob/master/Invoke-Build.ps1#L195 which checks the registry.

Microsoft have developed a couple of ways to get the MSBuild version from 15 onwards:

https://github.com/Microsoft/vssetup.powershell
https://github.com/Microsoft/vswhere

**Comment by nightroman** [comment]
For now, please use these Microsoft tools. I.e. get the MSBuild location and
set the alias *MSBuild* yourself, not by the IB helper `use`.

I am aware of this new challenge and I do not see an elegant solution. We can
use one of the suggested tools. But this is a dependency. So far this was not
needed and this was good.

I am looking at what other existing tools do. So far they simply guess a
typical location of VS 2017. I do not quite like this either. What if VS
was not installed in the default location?

Even with Microsoft tools not everything is clear to me. As far as understand,
they give VS location, not MSBuild location. So even with a proper VS path we
should use some "known" path like "MSBuild\15.0\Bin\MSBuild.exe" in there.
Or do I miss something and there is a more direct way?

I'll think of it for a while. Suggestions and ideas are very welcome.

**Comment by marking** [comment]
FWIW, the cake folks just assume the default install location: https://github.com/cake-build/cake/blob/3af06953bb2e668eab1ae83dad98cfceaf194552/src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs#L101

**Comment by cgibbons** [comment]
This is the approach I've taken using the supported module.  I just set my own msbuild variable.
https://github.com/Microsoft/vssetup.powershell

$msbuild = (Get-VSSetupInstance).InstallationPath + '\MSBuild\15.0\Bin\MsBuild.exe'

**Comment by nightroman** [comment]
@cgibbons Yes, I recommend this approach for the moment. *vssetup* module seems to be more natural for PowerShell than *vswhere*. Or this variation, perhaps a bit easier to use:

```powershell
Set-Alias MSBuild ((Get-VSSetupInstance).InstallationPath + '\MSBuild\15.0\Bin\MsBuild.exe')
```

**Comment by nightroman** [comment]
Here is the plan on how to deal with this issue. I will develop and publish a helper script, say, `Resolve-MSBuild.ps1`. The goals:

- Provide resolution for all MSBuild versions, including old (`VSSetup` and `vswhere` do not, at least now).
- Provide ability to resolve in the specified version scope or just get the latest available (from 4.0 to 15.0).
- For 15.0 and newer use the module `VSSetup` if it is installed, otherwise make some educated guesses about typical locations. The latter will work in many cases, so `VSSetup` will be needed only for not standard installations.
- `Invoke-Build` is not changed now. When `Resolve-MSBuild.ps1` stabilizes, we include it in the package and add an alias `Resolve-MSBuild` available for build scripts.
- The current approach `use <version> MSBuild` will be documented as obsolete.

**Comment by nightroman** [comment]
The script is published: https://www.powershellgallery.com/packages/Resolve-MSBuild

I will use and test it for a while. If all is fine, it will be included in the package and connected via an alias.
Feedback is welcome.

I would like this to be a separate script because it has some value on its own and may be used without Invoke-Build. Also, I predict that with future versions of MSBuild it is going to be somewhat too heavy in order to be in the engine directly.

**Comment by nightroman** [comment]
Invoke-Build v3.3.0 supports MSBuild 15.0.

Note that the old commands `use <version> MSBuild`, including `use *` continue to work. Internally they use the new command `Resolve-MSBuild`. The latter is recommended for new scripts. But developers may choose what they like more.
