### ISSUE TITLE
Error Action Override

### ISSUE THREAD

**Issue by lanrongwen** [nightroman/Invoke-Build#58]
I understand the concept of keeping Error Action to Stop, however, how can you override for 1 command and not a whole task?  I've tried setting ErrorActionPrefrence for the 1 command, and -ErrorAction and neither will set the behavior for only the command.

**Comment by nightroman** [comment]
It is a question about PowerShell rather than Invoke-Build. No problem, I just
mean you could ask this anywhere, e.g. StackOverflow.

> I've tried setting ErrorActionPrefrence for the 1 command, and -ErrorAction and neither will set the behavior for only the command.

It would be useful to see the example or get more details about your command in order to understand why this happens.

Some thoughts:

(1) There is a typo in `ErrorActionPrefrence` in your message. If you
copy/pasted it from your code, this typo may be the reason.

(2) Here is one way to change `$ErrorActionPreference` temporarily
in a task:

````powershell
    task ChangeErrorActionPreference {
        # it gets Stop, the default for Invoke-Build scripts
        "ErrorActionPreference before: $ErrorActionPreference"

        # invoke a command in a script block, i.e. in a new scope
        & {
            # set $ErrorActionPreference just for this scope
            $ErrorActionPreference = 'Continue'
            "ErrorActionPreference inside: $ErrorActionPreference"

            # invoke the command with an error, it emits not terminating error due
            # to local preference 'Continue', and the execution continues
            Get-Variable SomeMissingVariable
        }

        # it gets Stop again, we returned to the task scope
        "ErrorActionPreference after: $ErrorActionPreference"
    }
````

Build output shows the error preference before, inside, after, and the error inside:

````
    Build ChangeErrorActionPreference C:\tmp\_170408_063649_ib58\.build.ps1
    Task /ChangeErrorActionPreference
    ErrorActionPreference before: Stop
    ErrorActionPreference inside: Continue
    Get-Variable : Cannot find a variable with the name 'SomeMissingVariable'.
    At C:\tmp\_170408_063649_ib58\.build.ps1:14 char:3
    +         Get-Variable SomeMissingVariable
    +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (SomeMissingVariable:String) [Get-Variable], ItemNotFoundException
        + FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.GetVariableCommand

    ErrorActionPreference after: Stop
    Done /ChangeErrorActionPreference 00:00:00.1079660
    Build succeeded. 1 tasks, 0 errors, 0 warnings 00:00:00.2085832
````

**Comment by nightroman** [comment]
I am closing this as the answered question. Please feel free to reopen if you need more details.
