### ISSUE TITLE
Conditional Task not using Properties?

### ISSUE THREAD

**Issue by gaelcolas** [nightroman/Invoke-Build#59]
Hi Roman,

I'm trying to understand how the Build Task Parameters, that default to properties, behave when used in Task Conditions. Are properties calculated at task creation or at runtime?
How can a property be overridden by a task?

I have a Script task `blah.build.ps1` like so:

```PowerShell
Param (
    [string]
    $BuildSystem = (property BuildSystem 'blah')
}

task UploadUnitTestResultsToAppVeyor -If {Write-host "BuildSystem = $BuildSystem";
                                            Write-host "Env:BuildSystem = $Env:BuildSystem";
                                            $BuildSystem -eq 'AppVeyor' -or $Env:BuildSystem -eq 'AppVeyor'} {
    Write-Host "I'm in $BuildSystem"
}
```
This task is dot sourced from another build script, and the value of `$Env:BuildSystem` is set in another task that runs later, but it's not specified by the `Invoke-Build` command, nor set in the initial default task.

The behaviour I see is that $BuildSystem is set to 'blah', even if $Env:BuildSystem is set to 'Appveyor'.

You can see the actual file [here line 21](https://github.com/gaelcolas/SampleModule/blob/UnitTest/.build/Appveyor/TestResultUpload.Appveyor.build.ps1), and the [build in AppVeyor here, line 117](https://ci.appveyor.com/project/gaelcolas/samplemodule/build/1.0.34)

Thanks, let me know if I'm not clear. :)

**Comment by nightroman** [comment]
Per PowerShell rules, if the parameter `BuildSystem` is not specified then it is assigned to its default value specified by the expression `(property BuildSystem 'blah')`. This expression is invoked/evaluated before other code in the script.

> The behaviour I see is that $BuildSystem is set to 'blah', even if $Env:BuildSystem is set to 'Appveyor'.

This is the expected behaviour because `$Env:BuildSystem` is set to 'Appveyor' after the build script parameters evaluation.

You need the very latest `property` value in your task condition. Then just use `property` in your task condition:

````powershell
    Param (
        [string]
        $BuildSystem
    )

    task UploadUnitTestResultsToAppVeyor -If {(property BuildSystem 'blah') -eq 'AppVeyor'} {
        Write-Host "I'm in AppVeyor"
    }
````

Now `(property BuildSystem 'blah')` is evaluated on task invocation. It gets:

- the value of parameter `$BuildSystem` if it not null (specified as the parameter)
- otherwise `$env:BuildSystem` if it is set (any time before this point)
- otherwise 'blah' (the specified default)

Note that I removed `(property BuildSystem 'blah')` from the default parameter expression. You may or may not do this depending on your exact scenario and other usages of the parameter `BuildSystem` in your script. But per your description, it should be removed.

> Conditional Task not using Properties?

Your original code is not using `property` in the condition. It is using a plain variable. The suggested code is using `property` in the condition. Does it make sense?

**Comment by gaelcolas** [comment]
That makes perfect sense, thank you.

Somehow I was confused that the parameters were calculated at creation and changes not propagating, although that makes sense as well...

The way this works is so transparent and effortless that I just expected to be that way without thinking too much. 
Now fixed with your explanation :)

**Comment by nightroman** [comment]
@gaelcolas I created a new related issue https://github.com/nightroman/Invoke-Build/issues/60
