### ISSUE TITLE
new dsl word 'retrynr' & 'Invoke-RetryNrAction'

### ISSUE THREAD

**Issue by mwallner** [nightroman/Invoke-Build#64]
The current 'retry' and 'Invoke-RetryAction' has a big caveat: it's not really usable if the execution time of a given task may differ, but you want to ensure the task is run at least `<nr>` times before it fails.

**Comment by nightroman** [comment]
Thank you for the good idea and the PR with the ready solution. I have not tested it. But it looks neat and I will merge it soon.

Then I am going to rework it, so that the existing `Add-RetryTask` uses an extra parameter `RetryCount`. I think it is better to have one tool with two modes defined by different parameters than two similar tools for the same job with different parameters. As a result, a user of `retry` may switch the way of retrying by parameters without changing the tool name and dot-sourcing the different script.

**Comment by mwallner** [comment]
Was thinking the same (concerning only one Add-RetryTask) - but decided to create a new dsl-word for backward compatibility...

**Comment by nightroman** [comment]
We should not break anything by adding a new parameter to `retry`.

**Comment by mwallner** [comment]
I wasn't able to solve the problem concerning parameter order and coming up with a neat solution if both, Timeout and RetryCount were given, looking forward to your solution!

**Comment by nightroman** [comment]
I'll sort it out.

In fact, we can allow both modes defined simultaneously. A task is repeated until one of the defined is conditions is out. I.e. "retry max 10 times for max 600 seconds".

**Comment by mwallner** [comment]
Nice, but please note: I want to be able to completely disable the 'max 600 seconds' part.

I.e. I'll start UI-Tests on a Friday that take ~10+ hours .. if a test fails after some hours, I still want to retry it let's say two times before marking it as failed.

**Comment by nightroman** [comment]
I am thinking of the 3 modes

- `-RetryCount` = time does not matter
- `-RetryTimeout` = count does not matter
- both = whatever is out first

**Comment by nightroman** [comment]
Aha, I see it is tricky to upgrade semi-internal `Invoke-RetryAction` so that it is "nice" and backward compatible. Do you use it directly? I hope not.

I would redesign `Invoke-RetryAction`. Parameters `RetryCount`, `RetryTimeout`, `RetryInterval` should be named, not positional. In theory, it's a breaking change but hopefully, this function is not used directly.

**Comment by mwallner** [comment]
No, only using the dsl `retry` or `retrynr`, so changing `Invoke-RetryAction` would be ok for me - but you'll have to make the final decision on that I guess :D

**Comment by nightroman** [comment]
Changed as discussed. Please review and try. If all is fine then we can close it. Thank you for your help!

**Comment by mwallner** [comment]
LGTM, thanks! :-)
