### ISSUE TITLE
Error when using incremental/partial builds on PowerShell core

### ISSUE THREAD

**Issue by dbroeglin** [nightroman/Invoke-Build#69]
On PowerShell core on MacOSX: v6.0.0-alpha.18 or v6.0.0-beta.1 I get an error when trying an incremental or partial build like in the following example:
```
task clean {
    Get-ChildItem -Path dests | Remove-Item
}

task partial -Inputs {
    Get-ChildItem -Path sources 
} -Outputs {
    process {
        "dests/$((Get-Item $_).Name)"
    }
} -Partial {
    process {
        echo "source: $_, dest: $2"
        cp $_ $2
    }
}

task inc -Inputs {
    Get-ChildItem -Path sources 
} -Outputs { "dests/c.txt" } {
    process {
        echo "sources: $_"
        new-item "dests/c.txt" -Force > $Null
    }
}
```

Basically, if the destination files do not exist I get:

```
PS /tmp/titi> Invoke-Build clean, partial
Build clean, test /tmp/titi/Test.build.ps1
Task /clean
Done /clean 00:00:00.0084930
Task /partial
At /tmp/titi/Test.build.ps1:5 char:1
+ task test -Inputs {
+ ~~~~~~~~~~~~~~~~~~~
Build FAILED. 2 tasks, 1 errors, 0 warnings 00:00:00.0916690
/Users/dom/.local/share/powershell/Modules/InvokeBuild/3.3.8/Invoke-Build.ps1 : Exception calling "GetLastWriteTime" with "1" argument(s): "Could not find file '/tmp/titi/dests/a.txt'."
At line:1 char:1
+ Invoke-Build clean, partial
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Build.ps1], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException,Invoke-Build.ps1
```

The issue seems to be with the call to GetLastWriteTime that fails when the file does not exist:
```
[System.IO.File]::GetLastWriteTime("dests/a.txt")
System.IO.File]::GetLastWriteTime : The term 'System.IO.File]::GetLastWriteTime' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the nam
e, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ System.IO.File]::GetLastWriteTime("dests/a.txt")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (System.IO.File]::GetLastWriteTime:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

On Powershell 5.x on windows the method call does not fail but returns a very old date if the file does not exist.

**Comment by nightroman** [comment]
[dotnet/api]: https://docs.microsoft.com/en-us/dotnet/api/system.io.file.getlastwritetime?view=netframework-4.7#System_IO_File_GetLastWriteTime_System_String_
[Mono]: http://mapsbkp.geolives.com/monodoc/index.aspx?link=M%3ASystem.IO.File.GetLastWriteTime(System.String)
[Xamarin]: https://developer.xamarin.com/api/member/System.IO.File.GetLastWriteTime/p/System.String/

Thank you for the report. Per the description it should not be difficult to fix
or work around. But I would like to understand better where the real problem is.

(1)

Per [dotnet/api]

> If the file described in the path parameter does not exist, this method
returns 12:00 midnight, January 1, 1601 A.D. (C.E.) Coordinated Universal
Time (UTC), adjusted to local time.

Apparently on MacOS this API is different. How can we get to know if this is by
design or a bug? Is it .NET Mono or Xamarin?

[Mono] - There is "IOException - path was not found."

[Xamarin] - There is "IOException - path was not found."
At the same time the above remark also exists:

> If the file described in the path parameter does not exist, this method
returns 12:00 midnight, January 1, 1601 A.D. (C.E.) Coordinated Universal
Time (UTC), adjusted to local time.

(2)

Your posted error on `[System.IO.File]::GetLastWriteTime("dests/a.txt")` is weird.
Are you sure you used the correct command? It looks like the first `[` is missing,
according to the error message.

***

All is all, as far as Mono and Xamarin mention "IOException - path was not found."
it will be safer to adjust our Invoke-Build code in order to deal with this.

**Comment by nightroman** [comment]
v3.3.9 amends #70 (see comments there).

**Comment by dbroeglin** [comment]
You are right I cut and pasted the wrong bloc. I amended the issue for the correct message.
